### PR TITLE
Feature/posts

### PR DESCRIPTION
**Pull request by Eliacaterina**

### CODE REVIEW

**Comment by f3r** [comment]
@harrychenca do you get this trying to run it?

```
➜  connecTree git:(feature/posts) ✗ bundle install
Using rake 10.4.2
[etc]
Using web-console 2.1.2
Bundle complete! 16 Gemfile dependencies, 69 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

```
➜  connecTree git:(feature/posts) ✗ rails --version
Rails 4.2.1
```

```
➜  connecTree git:(feature/posts) ✗ rake db:migrate:status

database: connectree_dev

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20150601094832  Devise create users
   up     20150602062419  Create posts
```

```
➜  connecTree git:(feature/posts) ✗ rails s
=> Booting WEBrick
=> Rails 4.2.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2015-06-02 20:32:39] INFO  WEBrick 1.3.1
[2015-06-02 20:32:39] INFO  ruby 2.2.1 (2015-02-26) [x86_64-darwin14]
[2015-06-02 20:32:39] INFO  WEBrick::HTTPServer#start: pid=10302 port=3000


Started GET "/browser-sync/socket.io/?EIO=3&transport=polling&t=1433248363338-1835" for ::1 at 2015-06-02 20:32:43 +0800
  ActiveRecord::SchemaMigration Load (1.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"

ActionController::RoutingError (No route matches [GET] "/browser-sync/socket.io"):
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.1) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.1) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.1) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.1) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.1) lib/rack/lock.rb:17:in `call'
  rack (1.6.1) lib/rack/content_length.rb:15:in `call'
  rack (1.6.1) lib/rack/handler/webrick.rb:89:in `service'
  /Users/f3r/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/f3r/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/f3r/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'


  Rendered /Users/f3r/.rvm/gems/ruby-2.2.1@global/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.7ms)
  Rendered /Users/f3r/.rvm/gems/ruby-2.2.1@global/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/routes/_route.html.erb (2.0ms)
  Rendered /Users/f3r/.rvm/gems/ruby-2.2.1@global/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/routes/_table.html.erb (12.3ms)
  Rendered /Users/f3r/.rvm/gems/ruby-2.2.1@global/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (14.8ms)
  Rendered /Users/f3r/.rvm/gems/ruby-2.2.1@global/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (155.5ms)
  Rendered /Users/f3r/.rvm/gems/ruby-2.2.1@connecTree/gems/web-console-2.1.2/lib/web_console/templates/_markup.html.erb (0.5ms)
  Rendered /Users/f3r/.rvm/gems/ruby-2.2.1@connecTree/gems/web-console-2.1.2/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.5ms)
  Rendered /Users/f3r/.rvm/gems/ruby-2.2.1@connecTree/gems/web-console-2.1.2/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/f3r/.rvm/gems/ruby-2.2.1@connecTree/gems/web-console-2.1.2/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/f3r/.rvm/gems/ruby-2.2.1@connecTree/gems/web-console-2.1.2/lib/web_console/templates/console.js.erb within layouts/javascript (70.8ms)
  Rendered /Users/f3r/.rvm/gems/ruby-2.2.1@connecTree/gems/web-console-2.1.2/lib/web_console/templates/main.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/f3r/.rvm/gems/ruby-2.2.1@connecTree/gems/web-console-2.1.2/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.6ms)
  Rendered /Users/f3r/.rvm/gems/ruby-2.2.1@connecTree/gems/web-console-2.1.2/lib/web_console/templates/index.html.erb (162.0ms)
^C[2015-06-02 20:32:43] INFO  going to shutdown ...
[2015-06-02 20:32:44] INFO  WEBrick::HTTPServer#start done.
Exiting
```

**Comment by h8rry** [comment]
You don't need the `_helper.rb` files.

**Comment by h8rry** [comment]
You dont need `.coffee` files.

**Comment by h8rry** [comment]
Looks good :sun_with_face:

**Pull request merged**
